# Generated by Django 3.1.6 on 2021-09-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Brand'},
        ),
    ]
