# Generated by Django 3.1.6 on 2021-09-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('hot', 'hot'), ('bestseller', 'bestseller')], default='new', max_length=50),
        ),
    ]
