# Generated by Django 3.1.6 on 2021-09-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status_valid',
            field=models.DateTimeField(default='2021-9-12'),
            preserve_default=False,
        ),
    ]
